export const portugueseCoursesOnline = [

    {
        course: 'Introdução ao Front End',
        school: 'TIM Tec',
        time: '40 horas',
        finish: "22/05/2016",
        site: 'https://cursos.timtec.com.br/courses',
        degree: 'https://drive.google.com/open?id=0B8jNdEvSEyFZa0RRVjJaSFg4Q00',
    },
    {
        course: 'CSS3',
        school: 'TIM Tec',
        time: '40 horas',
        finish: "26/05/2016",
        site: 'https://cursos.timtec.com.br/courses',
        degree: 'https://drive.google.com/open?id=0B8jNdEvSEyFZcVBHZFlvb2QxXzg',
    },
    {
        course: 'JavaScript',
        school: 'TIM Tec',
        time: '40 horas',
        finish: "27/06/2016",
        site: 'https://cursos.timtec.com.br/courses',
        degree: 'https://drive.google.com/open?id=0B8jNdEvSEyFZYTRHeUpNQXhINVU',
    },
    {
        course: 'Java',
        school: 'TIM Tec',
        time: '40 horas',
        finish: "05/07/2016",
        site: 'https://cursos.timtec.com.br/courses',
        degree: 'https://drive.google.com/open?id=0B8jNdEvSEyFZcDkyRG9DQ291ZWM',
    },
    {
        course: 'HTML5',
        school: 'Curso em Vídeo',
        time: '40 horas',
        finish: "27/03/2017",
        site: 'https://www.cursoemvideo.com/course/',
        degree: 'https://drive.google.com/open?id=0B8jNdEvSEyFZM0NTeUZOTFVDTkU',
    },
    {
        course: 'MySQL',
        school: 'Curso em Vídeo',
        time: '40 horas',
        finish: "01/11/2017",
        site: 'https://www.cursoemvideo.com/course/',
        degree: 'https://drive.google.com/open?id=1ZbzjoMYX20Z4L7KbBAewjMCA1o5Sy5OF',
    },
    {
        course: 'Python 3 - Fundamentos',
        school: 'Curso em Vídeo',
        time: '40 horas',
        finish: "14/02/2018",
        site: 'https://www.cursoemvideo.com/course/',
        degree: 'hhttps://drive.google.com/open?id=1bcDat6KslbVOcwHWmoncLGEfRDwRP2yb',
    },
] 

export const englishCoursesOnline = [
    {
        course: 'Introdução ao Front End',
        school: 'TIM Tec',
        time: '40 horas',
        finish: "22/05/2016",
        site: 'https://cursos.timtec.com.br/courses',
        degree: 'https://drive.google.com/open?id=0B8jNdEvSEyFZa0RRVjJaSFg4Q00',
    },
    {
        course: 'CSS3',
        school: 'TIM Tec',
        time: '40 horas',
        finish: "26/05/2016",
        site: 'https://cursos.timtec.com.br/courses',
        degree: 'https://drive.google.com/open?id=0B8jNdEvSEyFZcVBHZFlvb2QxXzg',
    },
    {
        course: 'JavaScript',
        school: 'TIM Tec',
        time: '40 horas',
        finish: "27/06/2016",
        site: 'https://cursos.timtec.com.br/courses',
        degree: 'https://drive.google.com/open?id=0B8jNdEvSEyFZYTRHeUpNQXhINVU',
    },
    {
        course: 'Java',
        school: 'TIM Tec',
        time: '40 horas',
        finish: "05/07/2016",
        site: 'https://cursos.timtec.com.br/courses',
        degree: 'https://drive.google.com/open?id=0B8jNdEvSEyFZcDkyRG9DQ291ZWM',
    },
    {
        course: 'HTML5',
        school: 'Curso em Vídeo',
        time: '40 horas',
        finish: "27/03/2017",
        site: 'https://www.cursoemvideo.com/course/',
        degree: 'https://drive.google.com/open?id=0B8jNdEvSEyFZM0NTeUZOTFVDTkU',
    },
    {
        course: 'MySQL',
        school: 'Curso em Vídeo',
        time: '40 horas',
        finish: "01/11/2017",
        site: 'https://www.cursoemvideo.com/course/',
        degree: 'https://drive.google.com/open?id=1ZbzjoMYX20Z4L7KbBAewjMCA1o5Sy5OF',
    },
    {
        course: 'Python 3 - Fundamentos',
        school: 'Curso em Vídeo',
        time: '40 horas',
        finish: "14/02/2018",
        site: 'https://www.cursoemvideo.com/course/',
        degree: 'hhttps://drive.google.com/open?id=1bcDat6KslbVOcwHWmoncLGEfRDwRP2yb',
    },
    
] 

export const spanishCoursesOnline = [
    {
        course: 'Introdução ao Front End',
        school: 'TIM Tec',
        time: '40 horas',
        finish: "22/05/2016",
        site: 'https://cursos.timtec.com.br/courses',
        degree: 'https://drive.google.com/open?id=0B8jNdEvSEyFZa0RRVjJaSFg4Q00',
    },
    {
        course: 'CSS3',
        school: 'TIM Tec',
        time: '40 horas',
        finish: "26/05/2016",
        site: 'https://cursos.timtec.com.br/courses',
        degree: 'https://drive.google.com/open?id=0B8jNdEvSEyFZcVBHZFlvb2QxXzg',
    },
    {
        course: 'JavaScript',
        school: 'TIM Tec',
        time: '40 horas',
        finish: "27/06/2016",
        site: 'https://cursos.timtec.com.br/courses',
        degree: 'https://drive.google.com/open?id=0B8jNdEvSEyFZYTRHeUpNQXhINVU',
    },
    {
        course: 'Java',
        school: 'TIM Tec',
        time: '40 horas',
        finish: "05/07/2016",
        site: 'https://cursos.timtec.com.br/courses',
        degree: 'https://drive.google.com/open?id=0B8jNdEvSEyFZcDkyRG9DQ291ZWM',
    },
    {
        course: 'HTML5',
        school: 'Curso em Vídeo',
        time: '40 horas',
        finish: "27/03/2017",
        site: 'https://www.cursoemvideo.com/course/',
        degree: 'https://drive.google.com/open?id=0B8jNdEvSEyFZM0NTeUZOTFVDTkU',
    },
    {
        course: 'MySQL',
        school: 'Curso em Vídeo',
        time: '40 horas',
        finish: "01/11/2017",
        site: 'https://www.cursoemvideo.com/course/',
        degree: 'https://drive.google.com/open?id=1ZbzjoMYX20Z4L7KbBAewjMCA1o5Sy5OF',
    },
    {
        course: 'Python 3 - Fundamentos',
        school: 'Curso em Vídeo',
        time: '40 horas',
        finish: "14/02/2018",
        site: 'https://www.cursoemvideo.com/course/',
        degree: 'hhttps://drive.google.com/open?id=1bcDat6KslbVOcwHWmoncLGEfRDwRP2yb',
    },

    
] 

export const courses = [englishCoursesOnline, portugueseCoursesOnline, spanishCoursesOnline];
